added instructions to fix

diff --git a/docker/images/n8n/Dockerfile b/docker/images/n8n/Dockerfile
--- a/docker/images/n8n/Dockerfile
+++ b/docker/images/n8n/Dockerfile
@@ -8,7 +8,8 @@ FROM --platform=linux/amd64 n8nio/base:${NODE_VERSION} AS builder
 WORKDIR /src
 COPY . /src
 RUN --mount=type=cache,id=pnpm-store,target=/root/.local/share/pnpm/store --mount=type=cache,id=pnpm-metadata,target=/root/.cache/pnpm/metadata DOCKER_BUILD=true pnpm install --frozen-lockfile
-RUN pnpm build
+ENV NODE_OPTIONS='--max-old-space-size=16384'
+RUN pnpm build || (echo "Build failed, retrying with more debugging" && NODE_OPTIONS='--max-old-space-size=16384' pnpm build)
 
 # Delete all dev dependencies
 RUN jq 'del(.pnpm.patchedDependencies)' package.json > package.json.tmp; mv package.json.tmp package.json
